//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project11
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRESS_BOOK
    {
        public int USER_ID { get; set; }
        public string USERNAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string COUNTRY { get; set; }
        public string GENDER { get; set; }
        public Nullable<decimal> MO_NO_ { get; set; }
        public string JOBTITLE { get; set; }
    }
}
