//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project11
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MiralDBEntities : DbContext
    {
        public MiralDBEntities()
            : base("name=MiralDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SIGNUP> SIGNUPs { get; set; }
        public DbSet<VCARDTABLE> VCARDTABLEs { get; set; }
        public DbSet<ADDRESS_BOOK> ADDRESS_BOOK { get; set; }
        public DbSet<LOGIN> LOGINs { get; set; }
    
        public virtual ObjectResult<string> SP_ADDRESS_BOOK()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_ADDRESS_BOOK");
        }
    }
}
